import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 30,
    backgroundColor: '#F9F9F9',
    marginHorizontal: 10,
  },
  title: {
    fontSize: 30,
    marginBottom: 20,
    fontFamily: 'Pretendard-Bold',
    color: '#1A1A1A',
  },
  textInput: {
    height: 150,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    textAlignVertical: 'top',
    fontFamily: 'Pretendard-Regular',
    fontSize: 14,
    backgroundColor: '#fff',
  },
  resultContainer: {
    marginTop: 30,
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  resultTitle: {
    fontSize: 20,
    fontFamily: 'Pretendard-Bold',
    color: '#000',
  },
  result: {
    fontSize: 18,
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'Pretendard-Regular',
    marginTop: 10,
    color: '#1a1a1a',
  },
  resultButton: {
    backgroundColor: '#F0DEE0',
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 30,
    elevation: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 15,
    color: '#1A1A1A',
  },
  buttonText: {
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'Pretendard-Medium',
    color: '#1A1A1A',
  },
  musicContainer: {
    marginTop: 30,
    alignItems: 'center',
    padding: 20,
    backgroundColor: '#fff',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  musicTitle: {
    fontSize: 20,
    fontFamily: 'Pretendard-Bold',
    color: '#000',
  },
  musicImage: {
    width: 130,
    height: 130,
    marginTop: 15,
    borderRadius: 10,
  },
});

export default styles;
